language: go

go:
  - "1.13.x"

services:
  - docker

cache:
  directories:
    - $GOHOME

env:
  - GO111MODULE=on

before_script:
  - go get -v -t -d ./...

script:
  - go test -p 1 --tags=integration -v ./test/...